### ISSUE TITLE
Debugger gets dumped full of tween related errors when the player dies

### ISSUE THREAD

**Issue by VeryPuzzling** [hughbagan/wfc-roguelike#6]
The debugger gets flooded with errors when the player dies
notably, these include:
- E 0:00:56.124   tween_property: Type mismatch between property and final value: Nil and float
  <C++ Error>   Method failed. Returning: Ref<PropertyTweener>()
  <C++ Source>  scene/animation/scene_tree_tween.cpp:76 @ tween_property()
  <Stack Trace> Level.gd:164 @ _on_player_die()
- E 0:00:56.098   step: SceneTreeTween started, but has no Tweeners.
  <C++ Error>   Condition "tweeners.empty()" is true. Returned: false
  <C++ Source>  scene/animation/scene_tree_tween.cpp:270 @ step()

Version tested on: Windows
Steps to reproduce:
1. Start the game
2. Die to an enemy (was tested in a level)
3. Observe the debugger

**Comment by hughbagan** [comment]
Fixed by 9304dde3de91bf9a91f8d06b396853ad536f511c

The issue was I was trying to tween the wrong property on the text. Just removed that tween altogether since it wasn't necessary.
