### ISSUE TITLE
Blood vision momentarily appears when starting a level

### ISSUE THREAD

**Issue by VeryPuzzling** [hughbagan/wfc-roguelike#8]
Starting at level 2, blood vision will turn on for ~1s unprompted.

Versions tested on: Windows, [HTML not available](https://github.com/hughbagan/wfc-roguelike/issues/7)

Steps to reproduce:
1. Play the game until level 2
2. Observe

**Comment by hughbagan** [comment]
Reproduced on 9304dde3de91bf9a91f8d06b396853ad536f511c HTML build, Firefox and Chrome.

**Comment by hughbagan** [comment]
Fixed in https://github.com/hughbagan/wfc-roguelike/commit/af39965479b45068821711325917f3d199e726be. Problem was just the Enemy's RedLight being set to visible. Should be hidden to start.
